version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: btg_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: btg_pactual
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - btg_network

  # FastAPI Backend
  backend:
    build: .
    container_name: btg_backend
    restart: unless-stopped
    environment:
      # Database
      MONGODB_URL: mongodb://admin:password123@mongodb:27017/btg_pactual?authSource=admin
      DATABASE_NAME: ${DATABASE_NAME}
      
      # Security
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      
      # Application
      ENVIRONMENT: ${ENVIRONMENT}
      PROJECT_NAME: ${PROJECT_NAME}
      VERSION: ${VERSION}
      API_V1_STR: ${API_V1_STR}
      
      # CORS
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
      
      # Email Configuration (for notifications)
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_FROM: ${EMAIL_FROM}
      
      # Gmail SMTP Configuration (Free Tier)
      GMAIL_SMTP_USER: ${GMAIL_SMTP_USER}
      GMAIL_SMTP_PASSWORD: ${GMAIL_SMTP_PASSWORD}
      
      # Twilio Configuration (for SMS)
      TWILIO_ACCOUNT_SID: ${TWILIO_ACCOUNT_SID}
      TWILIO_AUTH_TOKEN: ${TWILIO_AUTH_TOKEN}
      TWILIO_FROM_PHONE: ${TWILIO_PHONE_NUMBER}
      TWILIO_PHONE_NUMBER: ${TWILIO_PHONE_NUMBER}
      
      # AWS Configuration (for deployment)
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/__pycache__
    networks:
      - btg_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # MongoDB Express (Admin UI)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: btg_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - btg_network

volumes:
  mongodb_data:
    driver: local

networks:
  btg_network:
    driver: bridge
